[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/saketkc/pysradb/blob/develop/notebooks/03.ParallelDownload.ipynb)

# Parallel Download

This notebook demonstrates how to download multiple SRA datasets in parallel using joblib.

In [1]:
# Install pysradb if not already installed
try:
    import pysradb

    print(f"pysradb {pysradb.__version__} is already installed")
except ImportError:
    print("Installing pysradb from GitHub...")
    import sys

    !{sys.executable} -m pip install -q git+https://github.com/saketkc/pysradb
    print("pysradb installed successfully!")

pysradb 3.0.0.dev0 is already installed

/home/runner/work/pysradb/pysradb/pysradb/download.py:15: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm

In [2]:
# pip install git+https://github.com/saketkc/pysradb

In [3]:
# joblib is included in the documentation environment

In [4]:
from joblib import Parallel, delayed

In [5]:
from pysradb.sraweb import SRAweb

db = SRAweb()

In [6]:
df = db.sra_metadata("SRP098789", detailed=True)
df

,run_accession,study_accession,study_title,experiment_accession,experiment_title,experiment_desc,organism_taxid,organism_name,library_name,library_strategy,...,treatment time,library type,ena_fastq_http,ena_fastq_http_1,ena_fastq_http_2,ena_fastq_ftp,ena_fastq_ftp_1,ena_fastq_ftp_2,study_geo_accession,experiment_geo_accession
0,SRR5227288,SRP098789,Selective stalling of human translation throug...,SRX2536403,"GSM2475997: 1.5 µM PF-067446846, 10 min, rep 1...","GSM2475997: 1.5 µM PF-067446846, 10 min, rep 1...",9606,Homo sapiens,NaN,OTHER,...,10 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/008...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2475997
1,SRR5227289,SRP098789,Selective stalling of human translation throug...,SRX2536404,"GSM2475998: 1.5 µM PF-067446846, 10 min, rep 2...","GSM2475998: 1.5 µM PF-067446846, 10 min, rep 2...",9606,Homo sapiens,NaN,OTHER,...,10 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/009...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2475998
2,SRR5227290,SRP098789,Selective stalling of human translation throug...,SRX2536405,"GSM2475999: 1.5 µM PF-067446846, 10 min, rep 3...","GSM2475999: 1.5 µM PF-067446846, 10 min, rep 3...",9606,Homo sapiens,NaN,OTHER,...,10 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/000...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2475999
3,SRR5227291,SRP098789,Selective stalling of human translation throug...,SRX2536406,"GSM2476000: 0.3 µM PF-067446846, 10 min, rep 1...","GSM2476000: 0.3 µM PF-067446846, 10 min, rep 1...",9606,Homo sapiens,NaN,OTHER,...,10 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/001...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476000
4,SRR5227292,SRP098789,Selective stalling of human translation throug...,SRX2536407,"GSM2476001: 0.3 µM PF-067446846, 10 min, rep 2...","GSM2476001: 0.3 µM PF-067446846, 10 min, rep 2...",9606,Homo sapiens,NaN,OTHER,...,10 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/002...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476001
5,SRR5227293,SRP098789,Selective stalling of human translation throug...,SRX2536408,"GSM2476002: 0.3 µM PF-067446846, 10 min, rep 3...","GSM2476002: 0.3 µM PF-067446846, 10 min, rep 3...",9606,Homo sapiens,NaN,OTHER,...,10 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/003...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476002
6,SRR5227294,SRP098789,Selective stalling of human translation throug...,SRX2536409,"GSM2476003: vehicle, 10 min rep 1; Homo sapien...","GSM2476003: vehicle, 10 min rep 1; Homo sapien...",9606,Homo sapiens,NaN,OTHER,...,10 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/004...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476003
7,SRR5227295,SRP098789,Selective stalling of human translation throug...,SRX2536410,"GSM2476004: vehicle, 10 min rep 2; Homo sapien...","GSM2476004: vehicle, 10 min rep 2; Homo sapien...",9606,Homo sapiens,NaN,OTHER,...,10 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/005...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476004
8,SRR5227296,SRP098789,Selective stalling of human translation throug...,SRX2536411,"GSM2476005: vehicle, 10 min rep 3; Homo sapien...","GSM2476005: vehicle, 10 min rep 3; Homo sapien...",9606,Homo sapiens,NaN,OTHER,...,10 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/006...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476005
9,SRR5227297,SRP098789,Selective stalling of human translation throug...,SRX2536412,"GSM2476006: 1.5 µM PF-067446846, 60 min, rep 1...","GSM2476006: 1.5 µM PF-067446846, 60 min, rep 1...",9606,Homo sapiens,NaN,OTHER,...,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/007...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476006
10,SRR5227298,SRP098789,Selective stalling of human translation throug...,SRX2536413,"GSM2476007: 1.5 µM PF-067446846, 60 min, rep 2...","GSM2476007: 1.5 µM PF-067446846, 60 min, rep 2...",9606,Homo sapiens,NaN,OTHER,...,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/008...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476007
11,SRR5227299,SRP098789,Selective stalling of human translation throug...,SRX2536414,"GSM2476008: 1.5 µM PF-067446846, 60 min, rep 3...","GSM2476008: 1.5 µM PF-067446846, 60 min, rep 3...",9606,Homo sapiens,NaN,OTHER,...,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/009...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476008
12,SRR5227300,SRP098789,Selective stalling of human translation throug...,SRX2536415,"GSM2476009: 0.3 µM PF-067446846, 60 min, rep 1...","GSM2476009: 0.3 µM PF-067446846, 60 min, rep 1...",9606,Homo sapiens,NaN,OTHER,...,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/000...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476009
13,SRR5227301,SRP098789,Selective stalling of human translation throug...,SRX2536416,"GSM2476010: 0.3 µM PF-067446846, 60 min, rep 2...","GSM2476010: 0.3 µM PF-067446846, 60 min, rep 2...",9606,Homo sapiens,NaN,OTHER,...,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/001...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476010
14,SRR5227302,SRP098789,Selective stalling of human translation throug...,SRX2536417,"GSM2476011: 0.3 µM PF-067446846, 60 min, rep 3...","GSM2476011: 0.3 µM PF-067446846, 60 min, rep 3...",9606,Homo sapiens,NaN,OTHER,...,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/002...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476011
15,SRR5227303,SRP098789,Selective stalling of human translation throug...,SRX2536418,"GSM2476012: vehicle, 60 min rep 1; Homo sapien...","GSM2476012: vehicle, 60 min rep 1; Homo sapien...",9606,Homo sapiens,NaN,OTHER,...,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/003...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476012
16,SRR5227304,SRP098789,Selective stalling of human translation throug...,SRX2536419,"GSM2476013: vehicle, 60 min rep 2; Homo sapien...","GSM2476013: vehicle, 60 min rep 2; Homo sapien...",9606,Homo sapiens,NaN,OTHER,...,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/004...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476013
17,SRR5227305,SRP098789,Selective stalling of human translation throug...,SRX2536420,"GSM2476014: vehicle, 60 min rep 3; Homo sapien...","GSM2476014: vehicle, 60 min rep 3; Homo sapien...",9606,Homo sapiens,NaN,OTHER,...,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/005...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476014
18,SRR5227306,SRP098789,Selective stalling of human translation throug...,SRX2536421,"GSM2476015: 1.5 µM PF-067446846, 60 min, rep 4...","GSM2476015: 1.5 µM PF-067446846, 60 min, rep 4...",9606,Homo sapiens,NaN,OTHER,...,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/006...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476015
19,SRR5227307,SRP098789,Selective stalling of human translation throug...,SRX2536422,"GSM2476016: Vehicle, 60 min, rep 4-ribo-seq; H...","GSM2476016: Vehicle, 60 min, rep 4-ribo-seq; H...",9606,Homo sapiens,NaN,RNA-Seq,...,60 min,Ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/007...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476016
20,SRR5227308,SRP098789,Selective stalling of human translation throug...,SRX2536423,"GSM2476017: 1.5 µM PF-067446846, 60 min, rep 5...","GSM2476017: 1.5 µM PF-067446846, 60 min, rep 5...",9606,Homo sapiens,NaN,OTHER,...,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/008...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476017
21,SRR5227309,SRP098789,Selective stalling of human translation throug...,SRX2536424,"GSM2476018: vehicle, 60 min, rep 5-Ribo-seq; H...","GSM2476018: vehicle, 60 min, rep 5-Ribo-seq; H...",9606,Homo sapiens,NaN,RNA-Seq,...,60 min,Ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/009...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476018
22,SRR5227310,SRP098789,Selective stalling of human translation throug...,SRX2536425,"GSM2476019: PF-06446846, 60 min, rep 4 -mRNA-s...","GSM2476019: PF-06446846, 60 min, rep 4 -mRNA-s...",9606,Homo sapiens,NaN,OTHER,...,60 min,mRNA-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/000...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476019
23,SRR5227311,SRP098789,Selective stalling of human translation throug...,SRX2536426,"GSM2476020: vehicle, 60 min, rep 4-mRNAseq; Ho...","GSM2476020: vehicle, 60 min, rep 4-mRNAseq; Ho...",9606,Homo sapiens,NaN,RNA-Seq,...,60 min,polyA-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/001...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476020
24,SRR5227312,SRP098789,Selective stalling of human translation throug...,SRX2536427,"GSM2476021: PF-06446846, 60 min, rep 5 -mRNA-s...","GSM2476021: PF-06446846, 60 min, rep 5 -mRNA-s...",9606,Homo sapiens,NaN,OTHER,...,60 min,mRNA-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/002...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476021
25,SRR5227313,SRP098789,Selective stalling of human translation throug...,SRX2536428,"GSM2476022: vehicle, 60 min, rep 5-mRNAseq; Ho...","GSM2476022: vehicle, 60 min, rep 5-mRNAseq; Ho...",9606,Homo sapiens,NaN,RNA-Seq,...,60 min,polyA-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/003...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476022

In [7]:
# randomply split into two dataframes
df1, df2 = df.iloc[:5, :], df.iloc[5:, :]

df2

,run_accession,study_accession,study_title,experiment_accession,experiment_title,experiment_desc,organism_taxid,organism_name,library_name,library_strategy,...,treatment time,library type,ena_fastq_http,ena_fastq_http_1,ena_fastq_http_2,ena_fastq_ftp,ena_fastq_ftp_1,ena_fastq_ftp_2,study_geo_accession,experiment_geo_accession
5,SRR5227293,SRP098789,Selective stalling of human translation throug...,SRX2536408,"GSM2476002: 0.3 µM PF-067446846, 10 min, rep 3...","GSM2476002: 0.3 µM PF-067446846, 10 min, rep 3...",9606,Homo sapiens,NaN,OTHER,...,10 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/003...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476002
6,SRR5227294,SRP098789,Selective stalling of human translation throug...,SRX2536409,"GSM2476003: vehicle, 10 min rep 1; Homo sapien...","GSM2476003: vehicle, 10 min rep 1; Homo sapien...",9606,Homo sapiens,NaN,OTHER,...,10 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/004...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476003
7,SRR5227295,SRP098789,Selective stalling of human translation throug...,SRX2536410,"GSM2476004: vehicle, 10 min rep 2; Homo sapien...","GSM2476004: vehicle, 10 min rep 2; Homo sapien...",9606,Homo sapiens,NaN,OTHER,...,10 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/005...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476004
8,SRR5227296,SRP098789,Selective stalling of human translation throug...,SRX2536411,"GSM2476005: vehicle, 10 min rep 3; Homo sapien...","GSM2476005: vehicle, 10 min rep 3; Homo sapien...",9606,Homo sapiens,NaN,OTHER,...,10 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/006...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476005
9,SRR5227297,SRP098789,Selective stalling of human translation throug...,SRX2536412,"GSM2476006: 1.5 µM PF-067446846, 60 min, rep 1...","GSM2476006: 1.5 µM PF-067446846, 60 min, rep 1...",9606,Homo sapiens,NaN,OTHER,...,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/007...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476006
10,SRR5227298,SRP098789,Selective stalling of human translation throug...,SRX2536413,"GSM2476007: 1.5 µM PF-067446846, 60 min, rep 2...","GSM2476007: 1.5 µM PF-067446846, 60 min, rep 2...",9606,Homo sapiens,NaN,OTHER,...,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/008...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476007
11,SRR5227299,SRP098789,Selective stalling of human translation throug...,SRX2536414,"GSM2476008: 1.5 µM PF-067446846, 60 min, rep 3...","GSM2476008: 1.5 µM PF-067446846, 60 min, rep 3...",9606,Homo sapiens,NaN,OTHER,...,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/009...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476008
12,SRR5227300,SRP098789,Selective stalling of human translation throug...,SRX2536415,"GSM2476009: 0.3 µM PF-067446846, 60 min, rep 1...","GSM2476009: 0.3 µM PF-067446846, 60 min, rep 1...",9606,Homo sapiens,NaN,OTHER,...,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/000...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476009
13,SRR5227301,SRP098789,Selective stalling of human translation throug...,SRX2536416,"GSM2476010: 0.3 µM PF-067446846, 60 min, rep 2...","GSM2476010: 0.3 µM PF-067446846, 60 min, rep 2...",9606,Homo sapiens,NaN,OTHER,...,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/001...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476010
14,SRR5227302,SRP098789,Selective stalling of human translation throug...,SRX2536417,"GSM2476011: 0.3 µM PF-067446846, 60 min, rep 3...","GSM2476011: 0.3 µM PF-067446846, 60 min, rep 3...",9606,Homo sapiens,NaN,OTHER,...,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/002...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476011
15,SRR5227303,SRP098789,Selective stalling of human translation throug...,SRX2536418,"GSM2476012: vehicle, 60 min rep 1; Homo sapien...","GSM2476012: vehicle, 60 min rep 1; Homo sapien...",9606,Homo sapiens,NaN,OTHER,...,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/003...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476012
16,SRR5227304,SRP098789,Selective stalling of human translation throug...,SRX2536419,"GSM2476013: vehicle, 60 min rep 2; Homo sapien...","GSM2476013: vehicle, 60 min rep 2; Homo sapien...",9606,Homo sapiens,NaN,OTHER,...,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/004...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476013
17,SRR5227305,SRP098789,Selective stalling of human translation throug...,SRX2536420,"GSM2476014: vehicle, 60 min rep 3; Homo sapien...","GSM2476014: vehicle, 60 min rep 3; Homo sapien...",9606,Homo sapiens,NaN,OTHER,...,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/005...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476014
18,SRR5227306,SRP098789,Selective stalling of human translation throug...,SRX2536421,"GSM2476015: 1.5 µM PF-067446846, 60 min, rep 4...","GSM2476015: 1.5 µM PF-067446846, 60 min, rep 4...",9606,Homo sapiens,NaN,OTHER,...,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/006...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476015
19,SRR5227307,SRP098789,Selective stalling of human translation throug...,SRX2536422,"GSM2476016: Vehicle, 60 min, rep 4-ribo-seq; H...","GSM2476016: Vehicle, 60 min, rep 4-ribo-seq; H...",9606,Homo sapiens,NaN,RNA-Seq,...,60 min,Ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/007...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476016
20,SRR5227308,SRP098789,Selective stalling of human translation throug...,SRX2536423,"GSM2476017: 1.5 µM PF-067446846, 60 min, rep 5...","GSM2476017: 1.5 µM PF-067446846, 60 min, rep 5...",9606,Homo sapiens,NaN,OTHER,...,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/008...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476017
21,SRR5227309,SRP098789,Selective stalling of human translation throug...,SRX2536424,"GSM2476018: vehicle, 60 min, rep 5-Ribo-seq; H...","GSM2476018: vehicle, 60 min, rep 5-Ribo-seq; H...",9606,Homo sapiens,NaN,RNA-Seq,...,60 min,Ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/009...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476018
22,SRR5227310,SRP098789,Selective stalling of human translation throug...,SRX2536425,"GSM2476019: PF-06446846, 60 min, rep 4 -mRNA-s...","GSM2476019: PF-06446846, 60 min, rep 4 -mRNA-s...",9606,Homo sapiens,NaN,OTHER,...,60 min,mRNA-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/000...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476019
23,SRR5227311,SRP098789,Selective stalling of human translation throug...,SRX2536426,"GSM2476020: vehicle, 60 min, rep 4-mRNAseq; Ho...","GSM2476020: vehicle, 60 min, rep 4-mRNAseq; Ho...",9606,Homo sapiens,NaN,RNA-Seq,...,60 min,polyA-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/001...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476020
24,SRR5227312,SRP098789,Selective stalling of human translation throug...,SRX2536427,"GSM2476021: PF-06446846, 60 min, rep 5 -mRNA-s...","GSM2476021: PF-06446846, 60 min, rep 5 -mRNA-s...",9606,Homo sapiens,NaN,OTHER,...,60 min,mRNA-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/002...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476021
25,SRR5227313,SRP098789,Selective stalling of human translation throug...,SRX2536428,"GSM2476022: vehicle, 60 min, rep 5-mRNAseq; Ho...","GSM2476022: vehicle, 60 min, rep 5-mRNAseq; Ho...",9606,Homo sapiens,NaN,RNA-Seq,...,60 min,polyA-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/003...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>,GSE94454,GSM2476022

In [8]:
def single_download(df_single):
    """Dry-run one download batch for executable documentation."""
    columns = ["run_accession", "study_accession", "experiment_accession"]
    return df_single[columns].assign(status="ready")

In [9]:
Parallel(n_jobs=2)(delayed(single_download)(df_x) for df_x in [df1, df2])

[  run_accession study_accession experiment_accession status
 0    SRR5227288       SRP098789           SRX2536403  ready
 1    SRR5227289       SRP098789           SRX2536404  ready
 2    SRR5227290       SRP098789           SRX2536405  ready
 3    SRR5227291       SRP098789           SRX2536406  ready
 4    SRR5227292       SRP098789           SRX2536407  ready,
    run_accession study_accession experiment_accession status
 5     SRR5227293       SRP098789           SRX2536408  ready
 6     SRR5227294       SRP098789           SRX2536409  ready
 7     SRR5227295       SRP098789           SRX2536410  ready
 8     SRR5227296       SRP098789           SRX2536411  ready
 9     SRR5227297       SRP098789           SRX2536412  ready
 10    SRR5227298       SRP098789           SRX2536413  ready
 11    SRR5227299       SRP098789           SRX2536414  ready
 12    SRR5227300       SRP098789           SRX2536415  ready
 13    SRR5227301       SRP098789           SRX2536416  ready
 14    SRR5227302       SRP098789           SRX2536417  ready
 15    SRR5227303       SRP098789           SRX2536418  ready
 16    SRR5227304       SRP098789           SRX2536419  ready
 17    SRR5227305       SRP098789           SRX2536420  ready
 18    SRR5227306       SRP098789           SRX2536421  ready
 19    SRR5227307       SRP098789           SRX2536422  ready
 20    SRR5227308       SRP098789           SRX2536423  ready
 21    SRR5227309       SRP098789           SRX2536424  ready
 22    SRR5227310       SRP098789           SRX2536425  ready
 23    SRR5227311       SRP098789           SRX2536426  ready
 24    SRR5227312       SRP098789           SRX2536427  ready
 25    SRR5227313       SRP098789           SRX2536428  ready]