[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/saketkc/pysradb/blob/master/notebooks/03.ParallelDownload.ipynb)

# Parallel Download

This notebook demonstrates how to download multiple SRA datasets in parallel using joblib.

In [1]:
# pip install git+https://github.com/saketkc/pysradb

In [2]:
pip install joblib

Requirement already satisfied: joblib in /home/saket/miniforge3/lib/python3.12/site-packages (1.5.2)
Note: you may need to restart the kernel to use updated packages.

In [3]:
from joblib import Parallel, delayed

In [4]:
from pysradb.sraweb import SRAweb

db = SRAweb()

/home/saket/miniforge3/lib/python3.12/site-packages/pysradb/utils.py:14: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm

In [5]:
df = db.sra_metadata("SRP098789", detailed=True)
df

,run_accession,study_accession,study_title,experiment_accession,experiment_title,experiment_desc,organism_taxid,organism_name,library_name,library_strategy,...,source_name,cell line,treatment time,library type,ena_fastq_http,ena_fastq_http_1,ena_fastq_http_2,ena_fastq_ftp,ena_fastq_ftp_1,ena_fastq_ftp_2
0,SRR5227288,SRP098789,Selective stalling of human translation throug...,SRX2536403,"GSM2475997: 1.5 µM PF-067446846, 10 min, rep 1...","GSM2475997: 1.5 µM PF-067446846, 10 min, rep 1...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_1.5 ÂµM PF-067446846_10 min_ribo-seq,Huh7,10 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/008...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
1,SRR5227289,SRP098789,Selective stalling of human translation throug...,SRX2536404,"GSM2475998: 1.5 µM PF-067446846, 10 min, rep 2...","GSM2475998: 1.5 µM PF-067446846, 10 min, rep 2...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_1.5 ÂµM PF-067446846_10 min_ribo-seq,Huh7,10 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/009...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
2,SRR5227290,SRP098789,Selective stalling of human translation throug...,SRX2536405,"GSM2475999: 1.5 µM PF-067446846, 10 min, rep 3...","GSM2475999: 1.5 µM PF-067446846, 10 min, rep 3...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_1.5 ÂµM PF-067446846_10 min_ribo-seq,Huh7,10 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/000...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
3,SRR5227291,SRP098789,Selective stalling of human translation throug...,SRX2536406,"GSM2476000: 0.3 µM PF-067446846, 10 min, rep 1...","GSM2476000: 0.3 µM PF-067446846, 10 min, rep 1...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_0.3 ÂµM PF-067446846_10 min_ribo-seq,Huh7,10 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/001...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
4,SRR5227292,SRP098789,Selective stalling of human translation throug...,SRX2536407,"GSM2476001: 0.3 µM PF-067446846, 10 min, rep 2...","GSM2476001: 0.3 µM PF-067446846, 10 min, rep 2...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_0.3 ÂµM PF-067446846_10 min_ribo-seq,Huh7,10 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/002...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
5,SRR5227293,SRP098789,Selective stalling of human translation throug...,SRX2536408,"GSM2476002: 0.3 µM PF-067446846, 10 min, rep 3...","GSM2476002: 0.3 µM PF-067446846, 10 min, rep 3...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_0.3 ÂµM PF-067446846_10 min_ribo-seq,Huh7,10 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/003...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
6,SRR5227294,SRP098789,Selective stalling of human translation throug...,SRX2536409,"GSM2476003: vehicle, 10 min rep 1; Homo sapien...","GSM2476003: vehicle, 10 min rep 1; Homo sapien...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_vehicle_10 min_ribo-seq,Huh7,10 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/004...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
7,SRR5227295,SRP098789,Selective stalling of human translation throug...,SRX2536410,"GSM2476004: vehicle, 10 min rep 2; Homo sapien...","GSM2476004: vehicle, 10 min rep 2; Homo sapien...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_vehicle_10 min_ribo-seq,Huh7,10 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/005...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
8,SRR5227296,SRP098789,Selective stalling of human translation throug...,SRX2536411,"GSM2476005: vehicle, 10 min rep 3; Homo sapien...","GSM2476005: vehicle, 10 min rep 3; Homo sapien...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_vehicle_10 min_ribo-seq,Huh7,10 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/006...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
9,SRR5227297,SRP098789,Selective stalling of human translation throug...,SRX2536412,"GSM2476006: 1.5 µM PF-067446846, 60 min, rep 1...","GSM2476006: 1.5 µM PF-067446846, 60 min, rep 1...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_1.5 ÂµM PF-067446846_60 min_ribo-seq,Huh7,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/007...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
10,SRR5227298,SRP098789,Selective stalling of human translation throug...,SRX2536413,"GSM2476007: 1.5 µM PF-067446846, 60 min, rep 2...","GSM2476007: 1.5 µM PF-067446846, 60 min, rep 2...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_1.5 ÂµM PF-067446846_60 min_ribo-seq,Huh7,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/008...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
11,SRR5227299,SRP098789,Selective stalling of human translation throug...,SRX2536414,"GSM2476008: 1.5 µM PF-067446846, 60 min, rep 3...","GSM2476008: 1.5 µM PF-067446846, 60 min, rep 3...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_1.5 ÂµM PF-067446846_60 min_ribo-seq,Huh7,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/009...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
12,SRR5227300,SRP098789,Selective stalling of human translation throug...,SRX2536415,"GSM2476009: 0.3 µM PF-067446846, 60 min, rep 1...","GSM2476009: 0.3 µM PF-067446846, 60 min, rep 1...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_0.3 ÂµM PF-067446846_60 min_ribo-seq,Huh7,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/000...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
13,SRR5227301,SRP098789,Selective stalling of human translation throug...,SRX2536416,"GSM2476010: 0.3 µM PF-067446846, 60 min, rep 2...","GSM2476010: 0.3 µM PF-067446846, 60 min, rep 2...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_0.3 ÂµM PF-067446846_60 min_ribo-seq,Huh7,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/001...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
14,SRR5227302,SRP098789,Selective stalling of human translation throug...,SRX2536417,"GSM2476011: 0.3 µM PF-067446846, 60 min, rep 3...","GSM2476011: 0.3 µM PF-067446846, 60 min, rep 3...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_0.3 ÂµM PF-067446846_60 min_ribo-seq,Huh7,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/002...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
15,SRR5227303,SRP098789,Selective stalling of human translation throug...,SRX2536418,"GSM2476012: vehicle, 60 min rep 1; Homo sapien...","GSM2476012: vehicle, 60 min rep 1; Homo sapien...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_vehicle_60 min_ribo-seq,Huh7,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/003...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
16,SRR5227304,SRP098789,Selective stalling of human translation throug...,SRX2536419,"GSM2476013: vehicle, 60 min rep 2; Homo sapien...","GSM2476013: vehicle, 60 min rep 2; Homo sapien...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_vehicle_60 min_ribo-seq,Huh7,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/004...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
17,SRR5227305,SRP098789,Selective stalling of human translation throug...,SRX2536420,"GSM2476014: vehicle, 60 min rep 3; Homo sapien...","GSM2476014: vehicle, 60 min rep 3; Homo sapien...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_vehicle_60 min_ribo-seq,Huh7,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/005...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
18,SRR5227306,SRP098789,Selective stalling of human translation throug...,SRX2536421,"GSM2476015: 1.5 µM PF-067446846, 60 min, rep 4...","GSM2476015: 1.5 µM PF-067446846, 60 min, rep 4...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_1.5 ÂµM PF-067446846_60 min_ribo-seq,Huh7,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/006...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
19,SRR5227307,SRP098789,Selective stalling of human translation throug...,SRX2536422,"GSM2476016: Vehicle, 60 min, rep 4-ribo-seq; H...","GSM2476016: Vehicle, 60 min, rep 4-ribo-seq; H...",9606,Homo sapiens,<NA>,RNA-Seq,...,Huh7_Veh_60 min_Ribo-seq,Huh7,60 min,Ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/007...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
20,SRR5227308,SRP098789,Selective stalling of human translation throug...,SRX2536423,"GSM2476017: 1.5 µM PF-067446846, 60 min, rep 5...","GSM2476017: 1.5 µM PF-067446846, 60 min, rep 5...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_1.5 ÂµM PF-067446846_60 min_ribo-seq,Huh7,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/008...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
21,SRR5227309,SRP098789,Selective stalling of human translation throug...,SRX2536424,"GSM2476018: vehicle, 60 min, rep 5-Ribo-seq; H...","GSM2476018: vehicle, 60 min, rep 5-Ribo-seq; H...",9606,Homo sapiens,<NA>,RNA-Seq,...,Huh7_vehcile_60 min_Ribo-seq,Huh7,60 min,Ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/009...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
22,SRR5227310,SRP098789,Selective stalling of human translation throug...,SRX2536425,"GSM2476019: PF-06446846, 60 min, rep 4 -mRNA-s...","GSM2476019: PF-06446846, 60 min, rep 4 -mRNA-s...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_PF-06446846_60 min_mRNA-seq,Huh7,60 min,mRNA-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/000...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
23,SRR5227311,SRP098789,Selective stalling of human translation throug...,SRX2536426,"GSM2476020: vehicle, 60 min, rep 4-mRNAseq; Ho...","GSM2476020: vehicle, 60 min, rep 4-mRNAseq; Ho...",9606,Homo sapiens,<NA>,RNA-Seq,...,Huh7_vehicle_60 min_RNA-seq,Huh7,60 min,polyA-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/001...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
24,SRR5227312,SRP098789,Selective stalling of human translation throug...,SRX2536427,"GSM2476021: PF-06446846, 60 min, rep 5 -mRNA-s...","GSM2476021: PF-06446846, 60 min, rep 5 -mRNA-s...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_PF-06446846_60 min_mRNA-seq,Huh7,60 min,mRNA-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/002...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
25,SRR5227313,SRP098789,Selective stalling of human translation throug...,SRX2536428,"GSM2476022: vehicle, 60 min, rep 5-mRNAseq; Ho...","GSM2476022: vehicle, 60 min, rep 5-mRNAseq; Ho...",9606,Homo sapiens,<NA>,RNA-Seq,...,Huh7_vehicle_60 min_RNA-seq,Huh7,60 min,polyA-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/003...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>

In [6]:
# randomply split into two dataframes
df1, df2 = df.iloc[:5, :], df.iloc[5:, :]

df2

,run_accession,study_accession,study_title,experiment_accession,experiment_title,experiment_desc,organism_taxid,organism_name,library_name,library_strategy,...,source_name,cell line,treatment time,library type,ena_fastq_http,ena_fastq_http_1,ena_fastq_http_2,ena_fastq_ftp,ena_fastq_ftp_1,ena_fastq_ftp_2
5,SRR5227293,SRP098789,Selective stalling of human translation throug...,SRX2536408,"GSM2476002: 0.3 µM PF-067446846, 10 min, rep 3...","GSM2476002: 0.3 µM PF-067446846, 10 min, rep 3...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_0.3 ÂµM PF-067446846_10 min_ribo-seq,Huh7,10 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/003...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
6,SRR5227294,SRP098789,Selective stalling of human translation throug...,SRX2536409,"GSM2476003: vehicle, 10 min rep 1; Homo sapien...","GSM2476003: vehicle, 10 min rep 1; Homo sapien...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_vehicle_10 min_ribo-seq,Huh7,10 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/004...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
7,SRR5227295,SRP098789,Selective stalling of human translation throug...,SRX2536410,"GSM2476004: vehicle, 10 min rep 2; Homo sapien...","GSM2476004: vehicle, 10 min rep 2; Homo sapien...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_vehicle_10 min_ribo-seq,Huh7,10 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/005...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
8,SRR5227296,SRP098789,Selective stalling of human translation throug...,SRX2536411,"GSM2476005: vehicle, 10 min rep 3; Homo sapien...","GSM2476005: vehicle, 10 min rep 3; Homo sapien...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_vehicle_10 min_ribo-seq,Huh7,10 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/006...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
9,SRR5227297,SRP098789,Selective stalling of human translation throug...,SRX2536412,"GSM2476006: 1.5 µM PF-067446846, 60 min, rep 1...","GSM2476006: 1.5 µM PF-067446846, 60 min, rep 1...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_1.5 ÂµM PF-067446846_60 min_ribo-seq,Huh7,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/007...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
10,SRR5227298,SRP098789,Selective stalling of human translation throug...,SRX2536413,"GSM2476007: 1.5 µM PF-067446846, 60 min, rep 2...","GSM2476007: 1.5 µM PF-067446846, 60 min, rep 2...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_1.5 ÂµM PF-067446846_60 min_ribo-seq,Huh7,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/008...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
11,SRR5227299,SRP098789,Selective stalling of human translation throug...,SRX2536414,"GSM2476008: 1.5 µM PF-067446846, 60 min, rep 3...","GSM2476008: 1.5 µM PF-067446846, 60 min, rep 3...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_1.5 ÂµM PF-067446846_60 min_ribo-seq,Huh7,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/009...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
12,SRR5227300,SRP098789,Selective stalling of human translation throug...,SRX2536415,"GSM2476009: 0.3 µM PF-067446846, 60 min, rep 1...","GSM2476009: 0.3 µM PF-067446846, 60 min, rep 1...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_0.3 ÂµM PF-067446846_60 min_ribo-seq,Huh7,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/000...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
13,SRR5227301,SRP098789,Selective stalling of human translation throug...,SRX2536416,"GSM2476010: 0.3 µM PF-067446846, 60 min, rep 2...","GSM2476010: 0.3 µM PF-067446846, 60 min, rep 2...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_0.3 ÂµM PF-067446846_60 min_ribo-seq,Huh7,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/001...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
14,SRR5227302,SRP098789,Selective stalling of human translation throug...,SRX2536417,"GSM2476011: 0.3 µM PF-067446846, 60 min, rep 3...","GSM2476011: 0.3 µM PF-067446846, 60 min, rep 3...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_0.3 ÂµM PF-067446846_60 min_ribo-seq,Huh7,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/002...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
15,SRR5227303,SRP098789,Selective stalling of human translation throug...,SRX2536418,"GSM2476012: vehicle, 60 min rep 1; Homo sapien...","GSM2476012: vehicle, 60 min rep 1; Homo sapien...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_vehicle_60 min_ribo-seq,Huh7,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/003...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
16,SRR5227304,SRP098789,Selective stalling of human translation throug...,SRX2536419,"GSM2476013: vehicle, 60 min rep 2; Homo sapien...","GSM2476013: vehicle, 60 min rep 2; Homo sapien...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_vehicle_60 min_ribo-seq,Huh7,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/004...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
17,SRR5227305,SRP098789,Selective stalling of human translation throug...,SRX2536420,"GSM2476014: vehicle, 60 min rep 3; Homo sapien...","GSM2476014: vehicle, 60 min rep 3; Homo sapien...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_vehicle_60 min_ribo-seq,Huh7,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/005...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
18,SRR5227306,SRP098789,Selective stalling of human translation throug...,SRX2536421,"GSM2476015: 1.5 µM PF-067446846, 60 min, rep 4...","GSM2476015: 1.5 µM PF-067446846, 60 min, rep 4...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_1.5 ÂµM PF-067446846_60 min_ribo-seq,Huh7,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/006...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
19,SRR5227307,SRP098789,Selective stalling of human translation throug...,SRX2536422,"GSM2476016: Vehicle, 60 min, rep 4-ribo-seq; H...","GSM2476016: Vehicle, 60 min, rep 4-ribo-seq; H...",9606,Homo sapiens,<NA>,RNA-Seq,...,Huh7_Veh_60 min_Ribo-seq,Huh7,60 min,Ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/007...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
20,SRR5227308,SRP098789,Selective stalling of human translation throug...,SRX2536423,"GSM2476017: 1.5 µM PF-067446846, 60 min, rep 5...","GSM2476017: 1.5 µM PF-067446846, 60 min, rep 5...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_1.5 ÂµM PF-067446846_60 min_ribo-seq,Huh7,60 min,ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/008...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
21,SRR5227309,SRP098789,Selective stalling of human translation throug...,SRX2536424,"GSM2476018: vehicle, 60 min, rep 5-Ribo-seq; H...","GSM2476018: vehicle, 60 min, rep 5-Ribo-seq; H...",9606,Homo sapiens,<NA>,RNA-Seq,...,Huh7_vehcile_60 min_Ribo-seq,Huh7,60 min,Ribo-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/009...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
22,SRR5227310,SRP098789,Selective stalling of human translation throug...,SRX2536425,"GSM2476019: PF-06446846, 60 min, rep 4 -mRNA-s...","GSM2476019: PF-06446846, 60 min, rep 4 -mRNA-s...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_PF-06446846_60 min_mRNA-seq,Huh7,60 min,mRNA-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/000...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
23,SRR5227311,SRP098789,Selective stalling of human translation throug...,SRX2536426,"GSM2476020: vehicle, 60 min, rep 4-mRNAseq; Ho...","GSM2476020: vehicle, 60 min, rep 4-mRNAseq; Ho...",9606,Homo sapiens,<NA>,RNA-Seq,...,Huh7_vehicle_60 min_RNA-seq,Huh7,60 min,polyA-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/001...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
24,SRR5227312,SRP098789,Selective stalling of human translation throug...,SRX2536427,"GSM2476021: PF-06446846, 60 min, rep 5 -mRNA-s...","GSM2476021: PF-06446846, 60 min, rep 5 -mRNA-s...",9606,Homo sapiens,<NA>,OTHER,...,Huh7_PF-06446846_60 min_mRNA-seq,Huh7,60 min,mRNA-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/002...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>
25,SRR5227313,SRP098789,Selective stalling of human translation throug...,SRX2536428,"GSM2476022: vehicle, 60 min, rep 5-mRNAseq; Ho...","GSM2476022: vehicle, 60 min, rep 5-mRNAseq; Ho...",9606,Homo sapiens,<NA>,RNA-Seq,...,Huh7_vehicle_60 min_RNA-seq,Huh7,60 min,polyA-seq,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR522/003...,<NA>,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR522/...,<NA>,<NA>

In [7]:
def single_download(df_single):
    db.download(df=df_single, skip_confirmation=True)

In [8]:
Parallel(n_jobs=2)(delayed(single_download)(df_x) for df_x in [df1, df2])

Checking download URLs
Checking download URLs
The following files will be downloaded:

run_accession study_accession experiment_accession public_url                                                                                                 download_url                                                                                          out_dir                                          filesize
SRR5227288    SRP098789       SRX2536403           https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos5/sra-pub-zq-11/SRR005/227/SRR5227288/SRR5227288.sralite.1 ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR522/SRR5227288/SRR5227288.sra /data/github/pysradb/notebooks/pysradb_downloads 533.5 MB
SRR5227289    SRP098789       SRX2536404           https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos5/sra-pub-zq-11/SRR005/227/SRR5227289/SRR5227289.sralite.1 ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR522/SRR5227289/SRR5227289.sra /data/github/pysradb/notebooks/pysradb_downloads 603.2 MB
SRR5227290    SRP098789       SRX2536405           https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos5/sra-pub-zq-11/SRR005/227/SRR5227290/SRR5227290.sralite.1 ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR522/SRR5227290/SRR5227290.sra /data/github/pysradb/notebooks/pysradb_downloads 586.1 MB
SRR5227291    SRP098789       SRX2536406                      https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos5/sra-pub-zq-14/SRR005/227/SRR5227291.sralite.1 ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR522/SRR5227291/SRR5227291.sra /data/github/pysradb/notebooks/pysradb_downloads 521.5 MB
SRR5227292    SRP098789       SRX2536407                      https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos5/sra-pub-zq-14/SRR005/227/SRR5227292.sralite.1 ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR522/SRR5227292/SRR5227292.sra /data/github/pysradb/notebooks/pysradb_downloads 871.3 MB


Total size: 3.1 GB

  0%|          | 0/5 [00:00<?, ?it/s]

The following files will be downloaded:

run_accession study_accession experiment_accession public_url                                                                                                 download_url                                                                                          out_dir                                          filesize
SRR5227293    SRP098789       SRX2536408                      https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos5/sra-pub-zq-14/SRR005/227/SRR5227293.sralite.1 ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR522/SRR5227293/SRR5227293.sra /data/github/pysradb/notebooks/pysradb_downloads 616.6 MB
SRR5227294    SRP098789       SRX2536409                      https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos5/sra-pub-zq-14/SRR005/227/SRR5227294.sralite.1 ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR522/SRR5227294/SRR5227294.sra /data/github/pysradb/notebooks/pysradb_downloads 962.4 MB
SRR5227295    SRP098789       SRX2536410                      https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos5/sra-pub-zq-14/SRR005/227/SRR5227295.sralite.1 ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR522/SRR5227295/SRR5227295.sra /data/github/pysradb/notebooks/pysradb_downloads 668.3 MB
SRR5227296    SRP098789       SRX2536411                      https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos5/sra-pub-zq-14/SRR005/227/SRR5227296.sralite.1 ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR522/SRR5227296/SRR5227296.sra /data/github/pysradb/notebooks/pysradb_downloads 755.3 MB
SRR5227297    SRP098789       SRX2536412                      https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos5/sra-pub-zq-14/SRR005/227/SRR5227297.sralite.1 ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR522/SRR5227297/SRR5227297.sra /data/github/pysradb/notebooks/pysradb_downloads 869.8 MB
SRR5227298    SRP098789       SRX2536413                      https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos5/sra-pub-zq-14/SRR005/227/SRR5227298.sralite.1 ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR522/SRR5227298/SRR5227298.sra /data/github/pysradb/notebooks/pysradb_downloads 681.0 MB
SRR5227299    SRP098789       SRX2536414                      https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos5/sra-pub-zq-14/SRR005/227/SRR5227299.sralite.1 ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR522/SRR5227299/SRR5227299.sra /data/github/pysradb/notebooks/pysradb_downloads 702.4 MB
SRR5227300    SRP098789       SRX2536415                      https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos5/sra-pub-zq-14/SRR005/227/SRR5227300.sralite.1 ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR522/SRR5227300/SRR5227300.sra /data/github/pysradb/notebooks/pysradb_downloads 438.7 MB
SRR5227301    SRP098789       SRX2536416                      https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos5/sra-pub-zq-14/SRR005/227/SRR5227301.sralite.1 ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR522/SRR5227301/SRR5227301.sra /data/github/pysradb/notebooks/pysradb_downloads 707.4 MB
SRR5227302    SRP098789       SRX2536417                      https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos5/sra-pub-zq-14/SRR005/227/SRR5227302.sralite.1 ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR522/SRR5227302/SRR5227302.sra /data/github/pysradb/notebooks/pysradb_downloads 642.3 MB
SRR5227303    SRP098789       SRX2536418                      https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos5/sra-pub-zq-14/SRR005/227/SRR5227303.sralite.1 ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR522/SRR5227303/SRR5227303.sra /data/github/pysradb/notebooks/pysradb_downloads 733.0 MB
SRR5227304    SRP098789       SRX2536419                      https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos5/sra-pub-zq-14/SRR005/227/SRR5227304.sralite.1 ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR522/SRR5227304/SRR5227304.sra /data/github/pysradb/notebooks/pysradb_downloads 682.1 MB
SRR5227305    SRP098789       SRX2536420                      https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos5/sra-pub-zq-14/SRR005/227/SRR5227305.sralite.1 ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR522/SRR5227305/SRR5227305.sra /data/github/pysradb/notebooks/pysradb_downloads 698.4 MB
SRR5227306    SRP098789       SRX2536421                      https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos5/sra-pub-zq-14/SRR005/227/SRR5227306.sralite.1 ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR522/SRR5227306/SRR5227306.sra /data/github/pysradb/notebooks/pysradb_downloads 838.8 MB
SRR5227307    SRP098789       SRX2536422                      https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos5/sra-pub-zq-14/SRR005/227/SRR5227307.sralite.1 ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR522/SRR5227307/SRR5227307.sra /data/github/pysradb/notebooks/pysradb_downloads 965.8 MB
SRR5227308    SRP098789       SRX2536423           https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos5/sra-pub-zq-11/SRR005/227/SRR5227308/SRR5227308.sralite.1 ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR522/SRR5227308/SRR5227308.sra /data/github/pysradb/notebooks/pysradb_downloads 953.1 MB
SRR5227309    SRP098789       SRX2536424                      https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos5/sra-pub-zq-14/SRR005/227/SRR5227309.sralite.1 ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR522/SRR5227309/SRR5227309.sra /data/github/pysradb/notebooks/pysradb_downloads 586.8 MB
SRR5227310    SRP098789       SRX2536425                      https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos5/sra-pub-zq-14/SRR005/227/SRR5227310.sralite.1 ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR522/SRR5227310/SRR5227310.sra /data/github/pysradb/notebooks/pysradb_downloads 965.6 MB
SRR5227311    SRP098789       SRX2536426                      https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos5/sra-pub-zq-14/SRR005/227/SRR5227311.sralite.1 ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR522/SRR5227311/SRR5227311.sra /data/github/pysradb/notebooks/pysradb_downloads 926.0 MB
SRR5227312    SRP098789       SRX2536427                      https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos5/sra-pub-zq-14/SRR005/227/SRR5227312.sralite.1 ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR522/SRR5227312/SRR5227312.sra /data/github/pysradb/notebooks/pysradb_downloads 846.2 MB
SRR5227313    SRP098789       SRX2536428                      https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos5/sra-pub-zq-14/SRR005/227/SRR5227313.sralite.1 ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR522/SRR5227313/SRR5227313.sra /data/github/pysradb/notebooks/pysradb_downloads   1.0 GB


Total size: 16.2 GB

100%|██████████| 5/5 [06:17<00:00, 75.54s/it]]
100%|██████████| 21/21 [25:17<00:00, 72.24s/it]

[None, None]